# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: mbedos/mbed-os-env:stable
    working_directory: ~
    steps:
      - checkout:
          path: EEE228
      - run: |
          cd EEE228/lock
          mbed deploy
          mbed compile -t ARMC6 -m KL46Z
